<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<AssemblyName>BbpSchemaDumper</AssemblyName>
		<OutputType>Exe</OutputType>
		<LangVersion>latest</LangVersion>
		<RootNamespace>BpBinReader</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="System.Reflection.MetadataLoadContext" Version="8.*" />
	</ItemGroup>
</Project>
